version: '3.1'
services:
#----------------------Message Bus Server---------------------------------#
  rabbitmq:
      hostname: 'rabbitmq'
      image: "rabbitmq:3-management"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "5672:5672"
        - "15672:15672"
      expose:
      - 5672
      - 15672  
      volumes:
        - 'rabbitmq_data:/data'  
#-----------MongoDB Server----------------- #
  mongo:
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - mongodb:/data/db
#------------MongoDB網頁版管理系統--------------------- #
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5469:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example               
#------------Message Broker--------------------- #
  message-broker-service:
      build: ./MessageBroker
      restart: always
      env_file:
      - ./docker-compose.env       
      depends_on:
        - mongo
        - rabbitmq    


#------------Web API--------------------- #
  web-api:
      build: ./WebAPI
      restart: always
      ports: 
        - 56969:5000
      env_file:
      - ./docker-compose.env       
      depends_on:
        - mongo
        - rabbitmq                
#-------------Persistent Volumes-------------------- #
volumes:
  mongodb:
  rabbitmq_data:     