version: '3.1'
services:
#-----------For Business DB, Event Store and Query DB----------------- #
  mongo:
    image: mongo
    restart: always
    ports:
            - 1769:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
            - mongodb:/data/db
#------------MongoDB網頁版管理系統--------------------- #
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5469:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example     
#-------------Persistent Volumes-------------------- #
volumes:
  mongodb:     